### ISSUE TITLE
Plex trigger for finished notifications

### ISSUE THREAD

**Issue by austinwbest** [Go-Lift-TV/notifiarr#36]
Add config values to the plex section

seriesPercentComplete = 90
moviePercentComplete = 95

Monitor plex api every minute for what is actively being watched and when the watched time / runtime >= the complete setting for the given type, send me a payload

**Comment by austinwbest** [comment]
You can start reading from https://discordapp.com/channels/764440599066574859/764441447445037086/826848255362990132 that point down a few messages to get a better understanding.

**Comment by davidnewhall** [comment]
oh fun.

**Comment by davidnewhall** [comment]
I don't see the runtime/time in the sessions payload. Where is it?

**Comment by austinwbest** [comment]
Here is what i use in the UI display for plex sessions...

```<label>Time:</label> <?= minutesToTime(ceil($session['offset'] / 60000)) .' / '. minutesToTime(ceil($session['duration'] / 60000)) ?>```

That will show

![image](https://user-images.githubusercontent.com/8321115/113464461-d9326e00-93fa-11eb-9a0e-ca1e81d897a3.png)

**Comment by davidnewhall** [comment]
I do not see `offset` in the json nor xml. I do see `viewOffset` that could be the right thing...

**Comment by austinwbest** [comment]
> I do not see `offset` in the json nor xml. I do see `viewOffset` that could be the right thing...

Likely so, I probably map it somewhere else

**Comment by davidnewhall** [comment]
Okay I have it outputting the percentage of each session every minute. What data do you want in the payload? Do I need to track which ones I've already sent and not send duplicates? Imaging it bing 94% and the next minute it's 95% and the next it's 96% until it goes away.
